### PR TITLE
Solves Issue #9

### PR DESCRIPTION
**Pull request by poliva83**
1. Added package_path attribute to chef-server-ingredient resource which will install package already on machine locally and avoid needing to internet access to `packagecloud.io/chef/stable`.
2. Added new test suite to test-kitchen called `local_package_install`.
3. Removed symbolic links to `spec_helper.rb` script as it does not work for test-kitchen that is running in windows environment. Switched to putting `spec_helper.rb` into common helpers folder instead.

### CODE REVIEW

**Comment by jtimberman** [comment]
Thank you for creating the issue and submitting the pull request. Before I comment on the actual code, first I want to talk about the purpose and direction of this cookbook.

The intention is that this cookbook is used to install the packages from a remote package repository. Package Cloud is what we're using, since we're primarily concerned with:

1 Consume the packages we provide, from the repository we provide.
2. We're using AWS EC2, and Package Cloud packages are served from S3.

I understand the concern with having internet access. Is there a particular reason to add the local package installation for the install action to this? Rather than using that in your own recipes? The `:install` action is really just a thin wrapper around creating the Package Cloud repository, and then installing the package. I think that this adds needless complexity to maintain in the future - there's more code to consider, more codepaths to test, and more attributes that a user needs to know about.

The `chef-server-ctl` command has an install option that can use local packages, too. But I don't really like that option either. Instead I'd rather add the capability of rendering a package repository configuration for a local repository with a template resource. Note I specifically say template because I'd rather not bring in the `apt` or `yum` cookbooks as dependencies.

**Comment by smith** [comment]
> Instead I'd rather add the capability of rendering a package repository configuration for a local repository with a template resource.

Can you explain the steps on how I would do that myself?

I was hoping this would get merged, but if not I'd like to know specifically how to specify local packages.

My use case is that I'm building and testing omnibus packages, and in the general case I'd like to install from Package Cloud, but if I've recently built a local package I'd like to test that instead.

**Comment by poliva83** [comment]
@jtimberman I appreciate you describing the purpose/intention of this cookbook. I don't want to derail the direction or make cookbook more complicated then it needs to be. 

I just created PR because chef-server-cluster uses this LWRP to install and reconfigure chef packages. I was not able to get around using that cookbook inside in certain locked down zones where I need a chef-server installed. Perhaps issue #9 is more appropriate to be created in that cookbook. I was hoping to not have fork both this cookbook and latter mentioned chef-server-cluster. With this change I am able to create a wrapper cookbook instead. Wrapper recipes could call recipes in chef-server-cluster and then modify chef-server-ingredient resources in compile phase to install package from local file and avoid external source.

```
The chef-server-ctl command has an install option that can use local packages, too.
```
Isn't there a chicken and egg problem with that as chef-server-ctl would not be available until you install chef server core package. So how does that get installed?

```Instead I'd rather add the capability of rendering a package repository configuration for a local repository with a template resource.```

This might be acceptable alternative long term. But not something that probably solves my issue in immediate future as its going to require completion of work from some other internal teams.

**Comment by jtimberman** [comment]
@poliva83 @smith I've done a more careful review of this, and I think it's fine since it merely uses packages already on disk, leaving it up to the user to provide their own mechanism to download them. I had some thoughts on making the code more concise and easier to reason about for future maintenance. Have a look in 9d12845.

**Comment by poliva83** [comment]
@jtimberman Your changes look good to me. :+1:  Thanks for considering the change.

**Pull request merged**
